### ISSUE TITLE
Customer CRUD

### ISSUE THREAD

**Issue by vitormattos** [LyseonTech/dashboard#2]
Create customer CRUD and add link to CRUD in the administrative menu.

### database requirements

customer (table name)
 - id_user
 - id_company
 - code
user (table name)
company (table name)

customer_user (table name)
id_customer
id_user

### Create customer
The user will enter the client code. Customer should be fetched from the Customer API. If the customer exists, the user will go to the screen to enter the customer details with the data already filled in. If the customer does not exist, does not perform registration.

NOTE: Only admin users can view this CRUD

#### CPF
 - [x] Name
 - [x] Email (only one)
 - [x] Phone (one only)
 - [x] Address (one only)

#### CNPJ
 - [x] Social reason
 - [x] municipal registration
 - [x] State registration
 - [x] Phone (one only)
 - [x] Address (one only)

**Comment by jrmalafaia** [comment]
Criado as Entidades:

- USER
- CUSTOMER
- CUSTOMER_USER
- COMPANY

USER

- Usuários de acesso ao painel
- Possui um ADM
- Se relaciona em N Clientes (customer_user)

CUSTOMER

- Cliente criado a partir de chave estrangeira importada da TBLCLIENTS (ambiente voip)
- Se for cliente empresa, grava também na COMPANY
- Relacionamento por associação com entidade USER (CUSTOMER_USER)

CUSTOMER_USER

- Tabela associativa entre CUSTOMER e USER "Um cliente pode ter vários usuários"

COMPANY

- Entidade relacionada a CUSTOMER pela chave estrangeira, atributo  id_company
