### ISSUE TITLE
Bootstrap with Laravel

### ISSUE THREAD

**Issue by vitormattos** [LyseonTech/dashboard#6]
The application backend will be developed using Laravel.

Implement project bootstrap with Laravel.

### Requirements
 - [x] All settings should be editable in .env file and the .env file should not be versioned.
 - [x] Log folder should be mapped to a volume
 - [x] Project README should be updated with all instructions needed to run the application.
 - [x] Update the composer.json file

**Comment by kathedrall** [comment]
To make the project more open and light, I was based on the laravel libraries but I am not using the framework as a whole. I called psr4 for autoload and pulled libraries like eloquent and twig

**Comment by vitormattos** [comment]
@kathedrall your PR solve the requirement for mapping log folder to a volume and updated the readme?

**Comment by vitormattos** [comment]
solved by pr #20
