### ISSUE TITLE
User CRUD

### ISSUE THREAD

**Issue by vitormattos** [LyseonTech/dashboard#7]
The user table created in issue #2 will be editable in users CRUD.

### Requirements
 - [x] Add link in menu for CRUD access
 - [x] Only system administrators access this CRUD.
 - [x] In addition to the user fields defined in task #2, it should be possible to associate the user with N customers.
 - [x] User password in create and reset user passowrd in edit

NOTE: Only admin users will be change user data.

**Comment by jrmalafaia** [comment]
Desenvolvida a entidade de usuários - **USER**
Onde:
- Armazenará os usuários de acesso ao painel
- Esses usuários terão relação com a entidade **CUSTOMER**, por meio de uma entidade associativa 
-  **CUSTOMER_USER**, com cardinalidade em 1-n (1 cliente para vários usuários).

Administrador
- Terá um usuário administrador para acesso irrestrito ao painel, onde poderá - impreterivelmente - acesso a criação de usuários, importação de cientes e associação usuário/cliente.
- Poderá redefinir senhas, alterar informações de clientes, excluir/adicionar/relacionar usuários.
